# Generated by Django 5.2.1 on 2025-06-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='child_profiles/'),
        ),
    ]
