# Generated by Django 5.2.1 on 2025-06-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_child_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_position', models.CharField(blank=True, max_length=50)),
                ('playing_background', models.TextField(blank=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('medical_issues', models.TextField(blank=True)),
                ('consent_signed', models.BooleanField(default=False)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='App.child')),
            ],
        ),
    ]
