# Generated by Django 5.2.1 on 2025-06-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_coach_user_alter_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age_group',
            field=models.CharField(choices=[('U8', 'Under 8'), ('U10', 'Under 10'), ('U12', 'Under 12'), ('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18')], default='U10', max_length=10),
        ),
        migrations.CreateModel(
            name='PlayerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=50)),
                ('spatial_awareness', models.IntegerField()),
                ('decision_making', models.IntegerField()),
                ('understanding_position', models.IntegerField()),
                ('off_the_ball_movement', models.IntegerField()),
                ('game_intelligence', models.IntegerField()),
                ('ball_control', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('tackling', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('teamwork', models.IntegerField()),
                ('discipline', models.IntegerField()),
                ('focus', models.IntegerField()),
                ('coach_summary', models.TextField()),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('suggested_drills', models.TextField()),
                ('short_term_goal', models.TextField()),
                ('long_term_goal', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.child')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.coach')),
            ],
        ),
    ]
