# Generated by Django 5.2.1 on 2025-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_child_age_group_playerassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
