# Generated by Django 5.2.1 on 2025-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_attendance_options_batch_attendance_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='preferred_position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('CDM', 'Defensive Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], max_length=20),
        ),
    ]
