# Generated by Django 5.2.1 on 2025-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_childprofile_preferred_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='age_group',
            field=models.CharField(choices=[('U8', 'Under 8'), ('U10', 'Under 10'), ('U12', 'Under 12'), ('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18')], max_length=20),
        ),
    ]
