# Generated by Django 5.2.1 on 2026-03-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_batch_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='App.batch'),
        ),
    ]
