# Generated by Django 5.2.1 on 2026-05-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_batch_end_time_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('child', 'batch', 'date')},
        ),
    ]
